import { Command } from "jsr:@cliffy/command@1.0.0-rc.7"
import { DtkError } from "../errors.js"
import { runPython } from "../python.js"

// The generator, relative to a dimos checkout. Finding this is also how the
// working directory is checked for being inside one: a pyproject.toml alone
// would match any python project on the machine.
const GENERATOR = "dimos/robot/test_all_blueprints_generation.py"

function dimosRootAbove(startPath) {
    let at = Deno.realPathSync(startPath)
    while (true) {
        try {
            Deno.statSync(`${at}/${GENERATOR}`)
            return at
        } catch (error) {
            // keep going
        }
        const up = at.replace(/\/[^/]*$/, "")
        if (up === at || up === "") {
            return null
        }
        at = up
    }
}

export default new Command()
    .name("gen_blue")
    .description("Regenerate dimos/robot/all_blueprints.py, from inside a dimos checkout")
    .action(async () => {
        const root = dimosRootAbove(Deno.cwd())
        if (root === null) {
            throw new DtkError(
                `dtk gen_blue: this only runs inside a dimos checkout, and ${Deno.cwd()} is not\n` +
                `     under one (nothing above it has ${GENERATOR}).`,
            )
        }
        console.error(`dtk: regenerating all_blueprints.py in ${root}`)
        // all_blueprints.py is generated by running its test, not by a script of
        // its own, so this is the supported way rather than a shortcut.
        const code = await runPython({
            module: "pytest",
            args: [`${root}/${GENERATOR}`],
            startPaths: [root],
            verbose: true,
        })
        if (code === 0) {
            console.error(`dtk: ${root}/dimos/robot/all_blueprints.py is up to date`)
        }
        Deno.exit(code)
    })
